services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
      - recording_data:/usr/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/vms
      - PORT=4000
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - LOG_LEVEL=debug
      - RECORDING_PATH=/usr/app/data
    depends_on:
      mongo:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      backend:
        condition: service_healthy


  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5
volumes:
  mongo_data:
  recording_data:
  

